main.out: add.o subtract.o multiply.o main.o
	gcc -o main.out add.o subtract.o multiply.o main.o

add.o: add.c
	gcc -c add.c

subtract.o: subtract.c
	gcc -c subtract.c

multiply.o: multiply.c
	gcc -c multiply.c

main.o: main.c
	gcc -c main.c


